### ISSUE TITLE
How does it handle DOM?

### ISSUE THREAD

**Issue by qq99** [EtienneLem/architect#4]
I see your proxy example is appending to the DOM from inside a worker (or from the function that you're sending the worker to execute).  I thought DOM wasn't available to the worker?

**Comment by EtienneLem** [comment]
DOM manipulation is indeed outside the worker. The proxy worker really only sends back data that it receives. It may sound unnecessary and overkill, but it does really help with the initial page load time. I haven’t had the time to properly benchmark it though, I’ll set up a test case and blog about in the near future.

**Comment by qq99** [comment]
Cool, I'd be interested to hear what you find out compared to regular XHR.  Definitely an interesting concept and I imagine it could be quite nice for batch rendering a huge collection of views on initial page load
