### ISSUE TITLE
Npm module ( https://npmjs.org ) 

### ISSUE THREAD

**Issue by obenjiro** [EtienneLem/architect#6]
Could you plz add it as an NPM module so i could easily install this awsome library with Node.js ?

**Comment by EtienneLem** [comment]
I wouldn’t mind, but I’d need some clue on where to start.

The great thing about Rails engines is that once the gem is included in the project, the said project has instant access to the gem’s assets (aka Architect CoffeeScript files), thanks to Sprockets.

I know that npm modules are also installed locally in `/node_modules`, but how does one access them when developing? Would you include it with a relative path? `../../../node_modules/architect/static/architect.min.js`. What’s the standard?

Thanks :P

**Comment by obenjiro** [comment]
Well. There is 2 patterns. You can use module on a server with Node.js:
1) npm install architect ( it will be installed in /node_modules/architect/ )
2) in code i just write ( var architect = require('architect'); )
3) PROFIT

``` javascript
//module usually looks like this 
var stringtoUpper = function (text) {

        return text.toUpperCase();

};

exports.toUpper = stringtoUpper;
```

and we using it like this 

``` javascript
var utils = require('./simple');

console.log(utils.toUpper('this is text'));
```

You also could use Browserify ( to load modules inside of a browser )
http://browserify.org
( it's better to read an explanation on that site )
Basicly it's just read all dependency inside of MAIN js file, and build one file.

About this topic I suggest you to read this first
http://visionmedia.github.io/masteringnode/book.html#Creating-Modules

And about creating a package
http://decodize.com/javascript/build-nodejs-npm-installation-package-scratch/

And here some links about NPM module system 
http://nodejs.org/api/modules.html

Hope this will help..
